export const notes = [
    {
        image: "/assets/javascript.svg",
        title: "Javascript",
        description: "",
        premium: false,
        difficulty: "Intermediate",
        href: "https://www.notion.so/HW-Javascript-1c56f33c367480538ce3d334def06cb8?pvs=4",
    },
    {
        image: "/assets/react.svg",
        title: "React JS",
        description: "",
        premium: false,
        difficulty: "Intermediate",
        href: "https://www.notion.so/HW-React-js-1ce6f33c367480479216c6b0c2f17f8b?pvs=4",
    },
    {
        image: "/assets/dsa.svg",
        title: "Data Structures",
        description: "",
        premium: false,
        difficulty: "Intermediate",
        href: "https://www.notion.so/HW-Data-Structures-1ce6f33c36748091a1bfd914ed503272?pvs=4",
    },
    {
        image: "/assets/algo.svg",
        title: "Algorithms",
        description: "",
        premium: false,
        difficulty: "Intermediate",
        href: "https://www.notion.so/HW-Algorithms-1ce6f33c36748002b33ec0b122f1dba6?pvs=4",
    },
    {
        image: "/assets/nodejs.svg",
        title: "Node JS",
        description: "",
        premium: false,
        difficulty: "Intermediate",
        href: "https://www.notion.so/HW-Node-js-1ce6f33c3674807ea4b5d3508d4a6757?pvs=4",
    },
    {
        image: "/assets/mongodb.svg",
        title: "Mongo DB",
        description: "",
        premium: false,
        difficulty: "Intermediate",
        href: "https://www.notion.so/HW-MongoDB-1ce6f33c367480f78c01d8aa9d2b3ff4?pvs=4",
    },
    {
        image: "/assets/mysql.svg",
        title: "My SQL",
        description: "",
        premium: false,
        difficulty: "Intermediate",
        href: "https://www.notion.so/HW-MySql-1ce6f33c36748047b503f7bdac4962ed?pvs=4",
    },
    {
        image: "/assets/oop.svg",
        title: "Object Oriented Programming",
        description: "",
        premium: false,
        difficulty: "Intermediate",
        href: "https://www.notion.so/HW-Object-Oriented-Programming-1ce6f33c3674807fb4a1c33d2e6c6aa6?pvs=4",
    },
];